[package]
name = "norem-lang"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
once_cell = "1.19.0"
im = "15.1.0"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
expect-test = "1.5.0"